version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: find-workers-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: find_workers
    volumes:
      - mongodb_data:/data/db
      - ./data/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - find-workers-network

volumes:
  mongodb_data:
    driver: local

networks:
  find-workers-network:
    driver: bridge